# Generated by Django 5.2.17 on 2026-10-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidacion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleliquidacion",
            name="unidades",
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name="liquidacion",
            name="numero",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
