# Generated by Django 5.2.17 on 2026-10-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plantilla_liquidacion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleplantillaliquidacion",
            name="unidades",
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
    ]
